### ISSUE TITLE
Kadet generator for Cronjob

### ISSUE THREAD

**Issue by alanhughes** [kapicorp/kapitan-reference#50]
Depends on https://github.com/kapicorp/kapitan-reference/pull/46/files

It would be great to be able to set application `type: cronjob`, along with a schedule, and generate a https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#cronjob-v1beta1-batch type configuration. 

The main implementation question I see with this concerns the fact that the Cronjob's spec.jobTemplate field is itself a [jobSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#jobspec-v1-batch), so it would be nice to reuse this, but all the configuration setting is hardcoded to happen at the root.spec level (like [here](https://github.com/kapicorp/kapitan-reference/pull/46/files#diff-24f5d17b2ca20fb26ec75cf141fbc774972dad87f706a435f1deea24db5b9c9aR389)), so moving it down to the root.spec.jobTemplate.spec level seems a bit fiddly.

**Comment by ademariag** [comment]
my intention would be to simply have a job definition and add a "cron" section to turn it into a cronjob, but I will look into it whatever makes it sane.
